"""Backward-compatible re-exports. Prefer ``eppa_viz.figures`` in new code."""

from eppa_viz.figures import (
    ChoroplethMap,
    DashboardFigure,
    FilteredInputOutputMappingPlot,
    FilteredOutputOutputMappingPlot,
    InputDistribution,
    InputDistributionAlternate,
    InputOutputMappingPlot,
    ModifyOutputTimeseries,
    NewTimeSeries,
    OldTimeSeries,
    OutputDistribution,
    OutputHistograms,
    OutputOutputMappingPlot,
    PermutationImportance,
    PlotTree,
    RegionalHeatmaps,
    TimeSeriesClusteringPlot,
    TimeSeriesClusteringPlotCART,
    ClusterOutputParcoordsPlot,
    TraceInfo,
    TreeNode,
    apply_finished_style,
    sanitize_uid,
)
