import pandas as pd
from plotly.colors import n_colors, hex_to_rgb, convert_dict_colors_to_same_type
import textwrap

class Color:
    def __init__(self):
        self.palette = {
            "Red 100": "2d0709",
            "Red 90": "520408",
            "Red 80": "750e13",
            "Red 70": "a2191f",
            "Red 60": "da1e28",
            "Red 50": "fa4d56",
            "Red 40": "ff8389",
            "Red 30": "ffb3b8",
            "Red 20": "ffd7d9",
            "Red 10": "fff1f1",
            "Magenta 100": "2a0a18",
            "Magenta 90": "510224",
            "Magenta 80": "740937",
            "Magenta 70": "9f1853",
            "Magenta 60": "d02670",
            "Magenta 50": "ee5396",
            "Magenta 40": "ff7eb6",
            "Magenta 30": "ffafd2",
            "Magenta 20": "ffdee8",
            "Magenta 10": "fff0f7",
            "Purple 100": "1c0f30",
            "Purple 90": "31135e",
            "Purple 80": "491d8b",
            "Purple 70": "6929c4",
            "Purple 60": "8a3ffc",
            "Purple 50": "a56eff",
            "Purple 40": "be95ff",
            "Purple 30": "d4bbff",
            "Purple 20": "e8daff",
            "Purple 10": "f6f2ff",
            "Blue 100": "001141",
            "Blue 90": "001d6c",
            "Blue 80": "002d9c",
            "Blue 70": "0043ce",
            "Blue 60": "0f62fe",
            "Blue 50": "4589ff",
            "Blue 40": "78a9ff",
            "Blue 30": "a6c8ff",
            "Blue 20": "d0e2ff",
            "Blue 10": "edf5ff",
            "Cyan 100": "061727",
            "Cyan 90": "012749",
            "Cyan 80": "003a6d",
            "Cyan 70": "00539a",
            "Cyan 60": "0072c3",
            "Cyan 50": "1192e8",
            "Cyan 40": "33b1ff",
            "Cyan 30": "82cfff",
            "Cyan 20": "bae6ff",
            "Cyan 10": "e5f6ff",
            "Teal 100": "081a1c",
            "Teal 90": "022b30",
            "Teal 80": "004144",
            "Teal 70": "005d5d",
            "Teal 60": "007d79",
            "Teal 50": "009d9a",
            "Teal 40": "08bdda",
            "Teal 30": "3ddbd9",
            "Teal 20": "9ef0f0",
            "Teal 10": "d9f9fb",
            "Green 100": "071908",
            "Green 90": "022d0d",
            "Green 80": "044317",
            "Green 70": "0e6027",
            "Green 60": "198038",
            "Green 50": "24a148",
            "Green 40": "42be65",
            "Green 30": "6fdc8c",
            "Green 20": "a7f0ba",
            "Green 10": "defbec",
            "Cool Gray 100": "121619",
            "Cool Gray 90": "21272a",
            "Cool Gray 80": "343a3f",
            "Cool Gray 70": "4d5358",
            "Cool Gray 60": "697077",
            "Cool Gray 50": "878d96",
            "Cool Gray 40": "a2a9b0",
            "Cool Gray 30": "c1c7cd",
            "Cool Gray 20": "dde1e6",
            "Cool Gray 10": "f2f4f8",
            "Gray 100": "161616",
            "Gray 90": "262626",
            "Gray 80": "393939",
            "Gray 70": "525252",
            "Gray 60": "6f6f6f",
            "Gray 50": "8d8d8d",
            "Gray 40": "a8a8a8",
            "Gray 30": "c6c6c6",
            "Gray 20": "e0e0e0",
            "Gray 10": "f4f4f4",
            "Warm Gray 100": "171414",
            "Warm Gray 90": "272525",
            "Warm Gray 80": "3c3838",
            "Warm Gray 70": "565151",
            "Warm Gray 60": "726e6e",
            "Warm Gray 50": "8f8b8b",
            "Warm Gray 40": "ada8a8",
            "Warm Gray 30": "cac5c4",
            "Warm Gray 20": "e5e0df",
            "Warm Gray 10": "f7f3f2"
            }
        self.hex_palette = {key: '#' + value for key, value in self.palette.items()}
        self.region_colors = {"GLB": "rgb(127, 127, 127)", "USA": "rgb(0, 83, 154)", "CAN": "rgb(162, 25, 31)", "MEX": "rgb(4, 67, 23)", "JPN": "rgb(250, 77, 86)",
                              "ANZ": "rgb(0, 67, 206)", "EUR": "rgb(255, 221, 0)", "ROE": "rgb(61, 219, 217)", "RUS": "rgb(1, 39, 73)", "ASI": "rgb(73, 29, 139)",
                              "CHN": "rgb(82, 4, 8)", "IND": "rgb(245, 222, 179)", "BRA": "rgb(111, 220, 140)", "AFR": "rgb(166, 200, 255)", "MES": "rgb(212, 187, 255)", 
                              "LAM": "rgb(0, 65, 68)", "REA": "rgb(130, 207, 255)", "KOR": "rgb(0, 93, 93)", "IDZ": "rgb(114, 110, 110)"}
        self.scenario_markers = {"Ref": "solid", "2C": "dot"}
        self.histogram_patterns = {"Ref": "", "2C": "/"}
        self.parallel_coords_colors = ["#785EF0", "#FFB000"]

    def generate_palette(self, n):
        rgb_colors = convert_dict_colors_to_same_type(self.hex_palette)
        return n_colors(rgb_colors["Red 80"], rgb_colors["Cool Gray 50"], n, colortype = "rgb")
    
    def convert_to_fill(self, color, alpha = 0.3):
        # add alpha channel
        fill_color = color[:3] + "a" + color[3:]
        # add alpha value
        fill_color = fill_color[:-1] + ", {})".format(alpha)
        return fill_color

class Readability:
    def __init__(self):
        self.readability_dict_backward = {
    "Carbon Price (USD2007 per ton CO2e)": "carbon_price_USD2007_per_ton_CO2e",
    "CPI Price Index": "CPI_price_index",
    "Electricity Production Biomass (No CCS, TWh)": "elec_prod_Biomass_No_CCS_TWh",
    "Electricity Production Coal (CCS, TWh)": "elec_prod_Coal_CCS_TWh",
    "Electricity Production Coal (No CCS, TWh)": "elec_prod_Coal_No_CCS_TWh",
    "Electricity Production Gas (CCS, TWh)": "elec_prod_Gas_CCS_TWh",
    "Electricity Production Gas (No CCS, TWh)": "elec_prod_Gas_No_CCS_TWh",
    "Electricity Production Hydro (TWh)": "elec_prod_Hydro_TWh",
    "Electricity Production Nuclear (TWh)": "elec_prod_Nuclear_TWh",
    "Electricity Production Oil (TWh)": "elec_prod_Oil_TWh",
    "Electricity Production Renewables (TWh)": "elec_prod_Renewables_TWh",
    "GDP (Billion USD2007)": "GDP_billion_USD2007",
    "Population (Million People)": "population_million_people",
    "Primary Energy Use Biomass (EJ)": "primary_energy_use_Biomass_EJ",
    "Primary Energy Use Coal (EJ)": "Primary_energy_use_Coal_EJ",
    "Primary Energy Use Gas (EJ)": "primary_energy_use_Gas_EJ",
    "Primary Energy Use Hydro (EJ)": "primary_energy_use_Hydro_EJ",
    "Primary Energy Use Nuclear (EJ)": "primary_energy_use_Nuclear_EJ",
    "Primary Energy Use Oil (EJ)": "primary_energy_use_Oil_EJ",
    "Primary Energy Use Renewables (EJ)": "primary_energy_use_Renewables_EJ",
    "Sectoral Emissions Agriculture (Million ton CO2e)": "sectoral_emi_Agriculture_million_ton_CO2e",
    "Sectoral Emissions Commercial Residential (Million ton CO2e)": "sectoral_emi_Commercial_Residential_million_ton_CO2e",
    "Sectoral Emissions Electricity (Million ton CO2e)": "sectoral_emi_Electricity_million_ton_CO2e",
    "Sectoral Emissions Energy Intensive Industry Mining (Million ton CO2e)": "sectoral_emi_EnergyIntensiveIndustry_Mining_million_ton_CO2e",
    "Sectoral Emissions Other Manufacturing (Million ton CO2e)": "sectoral_emi_Other_Manufacturing_million_ton_CO2e",
    "Sectoral Emissions Transportation (Million ton CO2e)": "sectoral_emi_Transportation_million_ton_CO2e",
    "Sectoral Output Agriculture (Billion USD2007)": "sectoral_output_Agriculture_billion_USD2007",
    "Sectoral Output Commercial Residential (Billion USD2007)": "sectoral_output_Commercial_Residential_billion_USD2007",
    "Sectoral Output Electricity (Billion USD2007)": "sectoral_output_Electricity_billion_USD2007",
    "Sectoral Output Energy Intensive Industry Mining (Billion USD2007)": "sectoral_output_EnergyIntensiveIndustry_Mining_billion_USD2007",
    "Sectoral Output Other Manufacturing (Billion USD2007)": "sectoral_output_Other_Manufacturing_billion_USD2007",
    "Sectoral Output Transportation (Billion USD2007)": "sectoral_output_Transportation_billion_USD2007",
    "Total Emissions CO2 (Million ton CO2)": "total_emissions_CO2_million_ton_CO2",
    "Total Emissions CO2e (Million ton CO2e)": "total_emissions_CO2e_million_ton_CO2e"
}
        self.readability_dict_forward = {v: k for k, v in self.readability_dict_backward.items()}
    
class Options:
    def __init__(self):
        self.region_names = ["GLB", "USA", "CAN", "MEX", "JPN", "ANZ", "EUR", "ROE", "RUS", "ASI", "CHN", "IND", 
                                "BRA", "AFR", "MES", "LAM", "REA", "KOR", "IDZ"]
        self.scenarios = ["Ref", "2C"]
        self.outputs = Readability().readability_dict_backward.values()
        self.years = [i for i in range(2020, 2101, 5)]
        self.markers = {"Ref": "circle", "2C": "triangle-up-open-dot"}
        self.input_names = [
                    "E-LK",
                    "E-NE(final)",
                    "E-NOE",
                    "ESUBE(EL/EI)",
                    "ESUBE(oth)",
                    "LK AGRI",
                    "LK ENOE",
                    "LK ELEC",
                    "LK EINT",
                    "LK SERV",
                    "LK OTHR",
                    "LK TRANS",
                    "LK DWE",
                    "LK FOOD",
                    "FF-COAL",
                    "FF-OIL",
                    "FF-GAS",
                    "VINT",
                    "AEEI USA",
                    "AEEI CAN",
                    "AEEI MEX",
                    "AEEI JPN",
                    "AEEI ANZ",
                    "AEEI EUR",
                    "AEEI ROE",
                    "AEEI RUS",
                    "AEEI ASI",
                    "AEEI KOR",
                    "AEEI IDZ",
                    "AEEI CHN",
                    "AEEI IND",
                    "AEEI BRA",
                    "AEEI AFR",
                    "AEEI MES",
                    "AEEI LAM",
                    "AEEI REA",
                    "oil",
                    "gas",
                    "coal",
                    "NGCC",
                    "PC",
                    "Nuclear",
                    "PV",
                    "wind",
                    "Bio",
                    "NGCAP",
                    "PCCAP",
                    "BioCCS",
                    "WindGas",
                    "WindBio",
                    "Biol-Oil",
                    "GDP",
                    "Pop",
                    "USA GDP",
                    "Non-USA GDP",
                    "USA Pop",
                    "Non-USA Pop",
                    "CHN GDP",
                    "Non-CHN GDP",
                    "CHN Pop",
                    "Non-CHN Pop",
                    "EUR GDP",
                    "Non-EUR GDP",
                    "EUR Pop",
                    "Non-EUR Pop",
                    "CAN GDP",
                    "Non-CAN GDP",
                    "CAN Pop",
                    "Non-CAN Pop",
                    "MEX GDP",
                    "Non-MEX GDP",
                    "MEX Pop",
                    "Non-MEX Pop",
                    "JPN GDP",
                    "Non-JPN GDP",
                    "JPN Pop",
                    "Non-JPN Pop",
                    "ANZ GDP",
                    "Non-ANZ GDP",
                    "ANZ Pop",
                    "Non-ANZ Pop",
                    "ROE GDP",
                    "Non-ROE GDP",
                    "ROE Pop",
                    "Non-ROE Pop",
                    "RUS GDP",
                    "Non-RUS GDP",
                    "RUS Pop",
                    "Non-RUS Pop",
                    "ASI GDP",
                    "Non-ASI GDP",
                    "ASI Pop",
                    "Non-ASI Pop",
                    "IND GDP",
                    "Non-IND GDP",
                    "IND Pop",
                    "Non-IND Pop",
                    "BRA GDP",
                    "Non-BRA GDP",
                    "BRA Pop",
                    "Non-BRA Pop",
                    "AFR GDP",
                    "Non-AFR GDP",
                    "AFR Pop",
                    "Non-AFR Pop",
                    "MES GDP",
                    "Non-MES GDP",
                    "MES Pop",
                    "Non-MES Pop",
                    "LAM GDP",
                    "Non-LAM GDP",
                    "LAM Pop",
                    "Non-LAM Pop",
                    "REA GDP",
                    "Non-REA GDP",
                    "REA Pop",
                    "Non-REA Pop",
                    "KOR GDP",
                    "Non-KOR GDP",
                    "KOR Pop",
                    "Non-KOR Pop",
                    "IDZ GDP",
                    "Non-IDZ GDP",
                    "IDZ Pop",
                    "Non-IDZ Pop"
                ]
        # in case
        # name = str(bound) + {1: 'st', 2: 'nd', 3: 'rd'}.get(4 if 10 <= bound % 100 < 20 else bound % 10, "th")
        self.filenames_to_sql_tables = {"carbon_price_USD2007_per_ton_CO2e": "carbon_price", "CPI_price_index": "cpi", "elec_prod_Biomass_No_CCS_TWh": "biomass_prod",
                                        "elec_prod_Coal_CCS_TWh": "coal_ccs_prod", "elec_prod_Coal_No_CCS_TWh": "coal_no_ccs_prod", "elec_prod_Gas_CCS_TWh": "gas_ccs_prod",
                                        "elec_prod_Gas_No_CCS_TWh": "gas_no_ccs_prod", "elec_prod_Hydro_TWh": "hydro_prod", "elec_prod_Nuclear_TWh": "nuclear_prod",
                                        "elec_prod_Oil_TWh": "oil_prod", "elec_prod_Renewables_TWh": "renewables_prod", "GDP_billion_USD2007": "gdp", "population_million_people": "population",
                                        "primary_energy_use_Biomass_EJ": "biomass_use", "Primary_energy_use_Coal_EJ": "coal_use", "primary_energy_use_Gas_EJ": "gas_use",
                                        "primary_energy_use_Hydro_EJ": "hydro_use", "primary_energy_use_Nuclear_EJ": "nuclear_use", "primary_energy_use_Oil_EJ": "oil_use",
                                        "primary_energy_use_Renewables_EJ": "renewables_use", "sectoral_emi_Agriculture_million_ton_CO2e": "agriculture_co2e",
                                        "sectoral_emi_Commercial_Residential_million_ton_CO2e": "residential_co2e", "sectoral_emi_Electricity_million_ton_CO2e": "electric_co2e",
                                        "sectoral_emi_EnergyIntensiveIndustry_Mining_million_ton_CO2e": "mining_co2e", "sectoral_emi_Other_Manufacturing_million_ton_CO2e": "manufacturing_co2e",
                                        "sectoral_emi_Transportation_million_ton_CO2e": "transportation_co2e", "sectoral_output_Agriculture_billion_USD2007": "agriculture_output", 
                                        "sectoral_output_Commercial_Residential_billion_USD2007": "residential_output", "sectoral_output_Electricity_billion_USD2007": "electric_output",
                                        "sectoral_output_EnergyIntensiveIndustry_Mining_billion_USD2007": "mining_output", "sectoral_output_Other_Manufacturing_billion_USD2007": "manufacturing_output",
                                        "sectoral_output_Transportation_billion_USD2007": "transportation_output", "total_emissions_CO2_million_ton_CO2": "emissions_co2", 
                                        "total_emissions_CO2e_million_ton_CO2e": "emissions_co2e"}